# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: docker build -t app

  - name: Run
    init: echo 'installing requirements'
    command: python -m pip install requirements.txt

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
- port: 3000
